services:
  db_api:
    image: mongo
    restart: always
    container_name: db_api
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

  api:
    build:
      context: api
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "3000:3000"
    # volumes:
    #   - ./api:/usr/src/app
    depends_on:
      - db_api

  front:
    build:
      context: front
      dockerfile: Dockerfile
    container_name: front
    ports:
      - "4200:4200"
    volumes:
      - ./front:/usr/src/app
    depends_on:
      - api